### PR TITLE
Improved networking statistics, better codebase structure.

### PR DESCRIPTION
**Pull request by grtcdr**
The networking statistics are currently Linux only, I'll have to look into how NetBSD works internally so we can have it working on there as well.

The codebase structure sees a reorganization, with the introduction of formatters found in the `fmt` directory, which are basically structs that have their own set of getters and setters as well as implementing fmt::Display. This helps keep the `read` crate clean and uniform, and it separates formatting from reading, for better readability and simplicity.

2021-12-07T02:26:08,666540249+01:00

### CODE REVIEW

**Comment by 0323pin** [comment]
For NetBSD, have a look at https://man.netbsd.org/netstat.1

**Comment by grtcdr** [comment]
> For NetBSD, have a look at https://man.netbsd.org/netstat.1

netstat looks like a great tool, but I'm more interested in how it works, so I guess I'll go over its sauce code.

**Comment by grtcdr** [comment]
Looks like [if_data](https://rust-lang.github.io/libc/x86_64-unknown-netbsd/doc/libc/struct.if_data.html) is the relevant struct for this kind of data.

**Comment by grtcdr** [comment]
The work in this PR is done, all that's left is to implement the extra information in libmacchina and then bump citron to the newer version. So I suppose I should merge the PR.

Hopefully I can figure out at some other time how to query the `if_data` structure as I can't find any examples online.

**Comment by 0323pin** [comment]
> Hopefully I can figure out at some other time how to query the if_data structure as I can't find any examples online.

you mean the Rusts libc if_data? I'm afraid I can't help much :(

**Comment by grtcdr** [comment]
Yeah, I couldn't find much on if_data, I'll look into it another day?

**Comment by 0323pin** [comment]
> Yeah, I couldn't find much on if_data, I'll look into it another day?

Take a break, no worries 😄 
You've been working hard!

Would you mind an OT question, though?
I'll e-mail you later.

**Comment by grtcdr** [comment]
> Take a break, no worries :smile:
>  You've been working hard!

Thanks pin! :smiley:

**Pull request merged**
